baseURL = "https://elliotchoi.com/"
title = "Elliot Choi"
languageCode = "en"

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[markup.goldmark.renderer]
unsafe = true

[params]
BookTheme = "light"
BookSection = "blogs"
BookSearch = true

[menu]
[[menu.home]]
name = "About"
pageRef = "/about/"
weight = 1

[[menu.home]]
name = "Papers"
pageRef = "/papers/"
weight = 2

[[menu.home]]
name = "CV"
url = "https://elliotchoi.com/files/Elliot_Choi_Resume.pdf"
weight = 3

[[menu.home]]
name = "Blog"
pageRef = "/blogs/"
weight = 4

[[menu.home]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/elliot-choi/"
weight = 5


